image:
  registry: docker.io
  repository: bitnami/thanos
  tag: 0.30.1-scratch-r0
  pullPolicy: IfNotPresent
objstoreConfig: |-  
  type: s3
  config:
    bucket: "testvn-prometheus"
    endpoint: "s3.ap-southeast-1.amazonaws.com"
    access_key: "AK11DV"
    secret_key: "1w91We8D"
    region: "ap-southeast-1"
    insecure: false
    signature_version2: false
    trace:
      enable: false
    part_size: 67108864

bucketweb:
  enabled: true

query:
  enabled: true
  logLevel: info
  logFormat: logfmt
  dnsDiscovery:
    enabled: true
  stores:
    - 10.200.12.226:10901
  replicaCount: 1

compactor:
  enabled: true
  retentionResolution5m: 90d

storegateway:
  enabled: true

ruler:
  enabled: false
  alertmanagers:
    - http://prometheus-operator-kube-p-alertmanager.hbc-monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="hbc-monitoring/prometheus-operator"})
            
  
