apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-dev
  name: nginx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
