apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxdev
  name: nginxdev-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxdev
  type: ClusterIP
