apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxdev
  name: nginxdev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxdev
  template:
    metadata:
      labels:
        app: nginxdev
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
